-- LexClaw Phase 2 seed metadata for plans + skills catalog
-- UUIDs should be generated by migration tooling in production.

-- Example plan seeds (upsert by code in real DB migration pipeline)
-- INSERT INTO plans (id, code, name) VALUES
--   (gen_random_uuid(), 'starter', 'Starter'),
--   (gen_random_uuid(), 'professional', 'Professional'),
--   (gen_random_uuid(), 'enterprise', 'Enterprise');

-- Example skill seeds
-- INSERT INTO skills_catalog (id, code, display_name, is_active) VALUES
--   (gen_random_uuid(), 'deposition-summarizer', 'Deposition Summarizer', true),
--   (gen_random_uuid(), 'contract-clause-risk-flagger', 'Clause Risk Flagger', true),
--   (gen_random_uuid(), 'deadline-extractor', 'Deadline Extractor', true),
--   (gen_random_uuid(), 'matter-intake-triage', 'Matter Intake Triage', true),
--   (gen_random_uuid(), 'pacer-search-adapter', 'PACER Search Adapter', true);
